import eslintConfigPrettier from "eslint-config-prettier";

export default [
  {
    ignores: ["node_modules/**", "**/node_modules/**"],
  },
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: "module",
      globals: {
        node: true,
        structuredClone: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        process: "readonly",
        Buffer: "readonly",
        globalThis: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        module: "readonly",
        require: "readonly",
        exports: "readonly",
        Promise: "readonly",
        Symbol: "readonly",
        BigInt: "readonly",
        Reflect: "readonly",
        WeakRef: "readonly",
        FinalizationRegistry: "readonly",
        queueMicrotask: "readonly",
        performance: "readonly",
        Intl: "readonly",
        JSON: "readonly",
        Math: "readonly",
        Proxy: "readonly",
        WeakMap: "readonly",
        WeakSet: "readonly",
        SharedArrayBuffer: "readonly",
        Atomics: "readonly",
        ArrayBuffer: "readonly",
        DataView: "readonly",
        Float32Array: "readonly",
        Float64Array: "readonly",
        Int8Array: "readonly",
        Int16Array: "readonly",
        Int32Array: "readonly",
        Uint8Array: "readonly",
        Uint16Array: "readonly",
        Uint32Array: "readonly",
        Uint8ClampedArray: "readonly",
        BigInt64Array: "readonly",
        BigUint64Array: "readonly",
        Map: "readonly",
        Set: "readonly",
        Array: "readonly",
        Object: "readonly",
        Function: "readonly",
        String: "readonly",
        Number: "readonly",
        Boolean: "readonly",
        Error: "readonly",
        TypeError: "readonly",
        RangeError: "readonly",
        SyntaxError: "readonly",
        URIError: "readonly",
        EvalError: "readonly",
        ReferenceError: "readonly",
        AggregateError: "readonly",
        Date: "readonly",
        RegExp: "readonly",
        parseInt: "readonly",
        parseFloat: "readonly",
        isNaN: "readonly",
        isFinite: "readonly",
        NaN: "readonly",
        Infinity: "readonly",
        undefined: "readonly",
        null: "readonly",
        MessageChannel: "readonly",
        MessagePort: "readonly",
        BroadcastChannel: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        atob: "readonly",
        btoa: "readonly",
        crypto: "readonly",
        SubtleCrypto: "readonly",
        WebSocket: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        EventTarget: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        CloseEvent: "readonly",
        MessageEvent: "readonly",
        ErrorEvent: "readonly",
        DOMException: "readonly",
        ResizeObserver: "readonly",
        ResizeObserverEntry: "readonly",
        IntersectionObserver: "readonly",
        IntersectionObserverEntry: "readonly",
        VisualViewport: "readonly",
        PerformanceObserver: "readonly",
        PerformanceMark: "readonly",
        PerformanceMeasure: "readonly",
        PerformanceEntry: "readonly",
        AggregateError: "readonly",
        ReadableStream: "readonly",
        WritableStream: "readonly",
        TransformStream: "readonly",
        CompressionStream: "readonly",
        DecompressionStream: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        FormData: "readonly",
        Request: "readonly",
        Response: "readonly",
        Headers: "readonly",
        Navigator: "readonly",
        navigator: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "off",
      "no-console": "off",
      "no-constant-condition": ["error", { checkLoops: false }],
    },
  },
  eslintConfigPrettier,
];